### ISSUE TITLE
Cannot open for ipad

### ISSUE THREAD

**Issue by ejjat0909** [Gabul-DEV/camera_camera#106]
i got this error when open the camera using ipad, it is working fine on iphone and android include tablet android

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      _RegisterFeScreenState._opencamera (package:fems_v5/screens/client/register_fe/register_fe_screen.dart:531:53)
<asynchronous suspension>
```

**Comment by gabuldev** [comment]
I will check this

**Comment by ejjat0909** [comment]
any update sir?
