### ISSUE TITLE
Can this be used in iOS Simulator?

### ISSUE THREAD

**Issue by chitgoks** [Gabul-DEV/camera_camera#94]
Hopefully deprecated code will be fixed. this is the only widget i could find and the best because the author literally didnt just create any ordinary widget.

Not really sure if it is a problem or not. I remember in Android, it works in the emulator.
But in the iOS Simulator i get this error
```

======== Exception caught by foundation library ====================================================
The following RangeError was thrown while dispatching notifications for CameraNotifier:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      CameraStatusSelected.actual (package:camera_camera/src/core/camera_status.dart:68:42)
#2      CameraStatusExt.when (package:camera_camera/src/core/camera_status.dart:143:43)
#3      _CameraCameraState.initState.<anonymous closure> (package:camera_camera/src/presentation/camera_page.dart:64:20)
#4      CameraNotifier.listen.<anonymous closure> (package:camera_camera/src/core/camera_notifier.dart:39:15)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:381:24)
#6      CameraNotifier.status= (package:camera_camera/src/core/camera_notifier.dart:34:5)
#7      CameraNotifier.changeCamera (package:camera_camera/src/core/camera_notifier.dart:70:7)
#8      CameraNotifier.init.<anonymous closure> (package:camera_camera/src/core/camera_notifier.dart:48:11)
#9      CameraStatusExt.when (package:camera_camera/src/core/camera_status.dart:134:27)
#10     CameraNotifier.init (package:camera_camera/src/core/camera_notifier.dart:45:12)
<asynchronous suspension>
The CameraNotifier sending notification was: Instance of 'CameraNotifier'
====================================================================================================
```

**Comment by gabuldev** [comment]
I will check this

**Comment by gabuldev** [comment]
The iOS simulator doesn't run the camera. If you need to test this, I recommend you use a real device for the test.
